# Variables.
PYTHON = python3

# Instala las dependencias del proyecto.
install:
	pip install requirements.txt

# Ejecuta el archivo principal del proyecto.
run:
	python /Autenticacion_para_todos/scr/Main.py

# Limpia los archivos generados durante la compilacion.
clean:
	rm -rf __pycache__*.pyc
